all:
	(cd poof-core; make $(MFLAGS) all)
	(cd poof-textui; make $(MFLAGS) all)
	(cd poof-support; make $(MFLAGS) all)
	(cd po-uilib; make $(MFLAGS) all)

clean:
	(cd poof-core; make $(MFLAGS) clean)
	(cd poof-textui; make $(MFLAGS) clean)
	(cd poof-support; make $(MFLAGS) clean)
	(cd po-uilib; make $(MFLAGS) clean)

install:
	(cd poof-core; make $(MFLAGS) install)
	(cd poof-textui; make $(MFLAGS) install)
	(cd poof-support; make $(MFLAGS) install)
	(cd po-uilib; make $(MFLAGS) install)